version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: simple-test-manager
    restart: unless-stopped
    environment:
      POSTGRES_USER: easyqa
      POSTGRES_PASSWORD: easyqa123
      POSTGRES_DB: easyqa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: